# Generated by Django 4.1.5 on 2023-01-28 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='物品名称')),
                ('desc', models.CharField(max_length=255, verbose_name='物品描述')),
                ('image', models.CharField(max_length=255, verbose_name='物品图片')),
                ('type', models.CharField(blank=True, choices=[('0', '默认'), ('1', '失物招领'), ('2', '寻物启事')], max_length=1)),
                ('status', models.CharField(blank=True, choices=[('0', '未完成'), ('1', '已完成')], max_length=1)),
                ('event_at', models.DateTimeField(auto_now=True)),
                ('event_place', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
            options={
                'verbose_name_plural': '发布信息表',
                'db_table': 'release',
            },
        ),
    ]
