# Generated by Django 4.1.7 on 2023-03-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='image',
            field=models.ImageField(upload_to='goods_image/', verbose_name='物品图片'),
        ),
    ]
