# Generated by Django 4.1.5 on 2023-01-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('nick_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('sex', models.CharField(blank=True, choices=[('0', '女'), ('1', '男')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': 'user',
            },
        ),
    ]
